/* HM_INVENTORY_STABLE_20260930_ANDROID_SECOND_3 */
/* Hello Majesty Inventory & Hunter */
let inventoryProducts=[], inventoryStock=[], inventoryView='stock';
let hunterDashboard=[];

async function loadInventoryData(){
  const [p,s]=await Promise.all([
    sb.from('product_master').select('*').eq('active',true).order('category').order('product'),
    sb.from(profile?.is_management?'stock_management':'stock_catalog').select('*').order('status').order('received_at',{ascending:false})
  ]);
  if(p.error) throw p.error; if(s.error) throw s.error;
  inventoryProducts=p.data||[]; inventoryStock=s.data||[];
}

async function renderInventory(){
  const host=document.getElementById('inventoryPanel')||document.createElement('div');
  host.id='inventoryPanel';host.className='box';
  const dash=document.getElementById('dashboard'),stats=document.getElementById('stats');
  if(dash&&!dash.contains(host))dash.insertBefore(host,stats||null);
  try{await loadInventoryData();}catch(e){
    console.error('[HM] Inventory load error',e);
    host.innerHTML='<h2 style="margin:0">📦 PRODUCT & STOCK</h2><p class="small" style="margin-top:10px">Product & Stock gagal memuat data.</p><div class="box"><b>Error:</b> '+esc(e?.message||e)+'</div><button class="secondary" onclick="refreshInventory(this)">↻ Coba Lagi</button>';
    return;
  }
  const ready=inventoryStock.filter(x=>x.status==='READY').length;
  const sold=inventoryStock.filter(x=>x.status==='SOLD').length;
  const reserved=inventoryStock.filter(x=>x.status==='RESERVED').length;
  const service=inventoryStock.filter(x=>x.status==='SERVICE').length;
  const canManage=!!profile?.is_management || String(profile?.role||'').toUpperCase()==='FASILITATOR' || (Array.isArray(window.hmRoles) && window.hmRoles.some(r=>String(r).toUpperCase()==='FASILITATOR'));
  host.innerHTML='<div class="row" style="justify-content:space-between;align-items:center"><div><h2 style="margin:0">📦 PRODUCT & STOCK</h2><div class="small">Database produk untuk CS/Sales + kontrol inventory Management</div></div><div class="row"><button class="secondary" onclick="refreshInventory(this)">↻ Refresh</button>'+(canManage?'<button class="secondary" onclick="openProductMaster()">⚙️ Master Produk</button>':'')+ '<button class="success" onclick="openReceiveStock()">＋ BARANG MASUK</button></div></div>'+
  '<div class="stats" style="margin-top:10px">'+
  invStat('🟢 Ready',ready)+invStat('🔴 Terjual',sold)+invStat('🟡 Reserved',reserved)+invStat('🔧 Service',service)+invStat('📦 Total',inventoryStock.length)+'</div>'+
  '<div class="row" style="margin-top:12px"><button class="'+(inventoryView==='stock'?'':'secondary')+'" id="invStockTab" type="button" data-inventory-view="stock">Stock</button><button class="'+(inventoryView==='products'?'':'secondary')+'" id="invProductsTab" type="button" data-inventory-view="products">Produk</button><button class="secondary" onclick="openSalesReport()">Penjualan</button>'+''+(canManage?'<button class="secondary" onclick="openHunterCommission()">💸 Komisi</button>':'')+'</div>'+
  '<div id="inventoryViewDebug" class="small" style="margin-top:8px;font-weight:700"></div><div id="inventoryBody" style="margin-top:10px"></div>';
  host.onclick=(e)=>{const tab=e.target.closest('[data-inventory-view]');if(tab){e.preventDefault();setInventoryView(tab.dataset.inventoryView)}};
  renderInventoryBody();
}
async function refreshInventory(btn){if(btn?.disabled)return;try{if(btn){btn.disabled=true;btn.textContent='⏳ Loading...'}await renderInventory()}catch(e){console.error(e);alert('Refresh Product & Stock error: '+(e?.message||e))}finally{if(btn){btn.disabled=false;btn.textContent='↻ Refresh'}}}
async function loadHunterDashboard(){const r=await sb.from('hunter_dashboard').select('*').order('total_commission',{ascending:false});if(r.error)throw r.error;hunterDashboard=r.data||[]}
function fmtRp(v){return 'Rp'+Number(v||0).toLocaleString('id-ID')}
async function markHunterCommissionPaid(id){if(!profile?.is_management)return alert('Akses Management diperlukan.');const note=prompt('Catatan pembayaran (opsional):')||null;const r=await sb.from('sales_transactions').update({hunter_commission_paid_at:new Date().toISOString(),hunter_commission_paid_by:profile.user_id,hunter_commission_payment_note:note}).eq('id',id).is('hunter_commission_paid_at',null);if(r.error)return alert(r.error.message);openHunterCommission()}
async function openHunterCommission(){const r=await sb.from('sales_transactions').select('id,sold_at,hunter_user_id,hunter_commission,hunter_commission_paid_at,hunter_commission_payment_note,customer_name').not('hunter_user_id','is',null).order('sold_at',{ascending:false});if(r.error)return alert(r.error.message);const teams=await sb.from('team_directory').select('user_id,name');const names=Object.fromEntries((teams.data||[]).map(x=>[x.user_id,x.name]));const rows=r.data||[];$('mt').textContent='💸 Komisi Hunter';$('mb').innerHTML='<div class="small" style="margin-bottom:10px">Komisi 10% dari profit unit Hunter yang SOLD. Pembayaran hanya dapat diubah oleh Management.</div>'+rows.map(x=>'<div class="lead"><b>🏹 '+esc(names[x.hunter_user_id]||'Unknown')+'</b><div>'+new Date(x.sold_at).toLocaleDateString('id-ID')+' • Komisi <b>'+fmtRp(x.hunter_commission)+'</b></div><div class="small">'+(x.hunter_commission_paid_at?'🟢 Dibayar '+new Date(x.hunter_commission_paid_at).toLocaleDateString('id-ID'):'🟡 Belum dibayar')+'</div>'+((profile?.is_management&&!x.hunter_commission_paid_at)?'<button class="success" style="margin-top:6px" onclick="markHunterCommissionPaid(\''+x.id+'\')">✓ Tandai Sudah Dibayar</button>':'')+'</div>').join('')||'<p class="small">Belum ada transaksi komisi Hunter.</p>';$('modal').classList.remove('hidden')}
async function openHunterDashboard(){try{await loadHunterDashboard()}catch(e){alert(e.message||e);return}$('mt').textContent='🏹 Dashboard Hunter';$('mb').innerHTML='<div class="small" style="margin-bottom:10px">Komisi = 10% dari profit unit Hunter yang sudah SOLD.</div>'+hunterDashboard.map(h=>'<div class="lead"><div class="row" style="justify-content:space-between"><b>🏹 '+esc(h.hunter_name)+'</b><span class="badge">'+h.sold_units+' SOLD</span></div><div style="margin-top:8px">📦 Total unit: <b>'+h.total_units+'</b> • 🟢 Ready: <b>'+h.ready_units+'</b> • 🔴 Sold: <b>'+h.sold_units+'</b></div><div style="margin-top:5px">💰 Profit: <b>'+fmtRp(h.total_profit)+'</b> • 🎯 Komisi: <b>'+fmtRp(h.total_commission)+'</b></div></div>').join('')||'<p class="small">Belum ada stock Hunter.</p>';$('modal').classList.remove('hidden')}
function invStat(label,val){return '<div class="stat"><div class="small">'+label+'</div><div class="num">'+Number(val||0).toLocaleString('id-ID')+'</div></div>'}
function setInventoryView(view){inventoryView=view;renderInventoryBody();const dbg=document.getElementById('inventoryViewDebug');if(dbg)dbg.textContent='Mode: '+(view==='products'?'PRODUK':'STOCK');const panel=document.getElementById('inventoryPanel');if(panel){const buttons=panel.querySelectorAll('.row button');buttons.forEach(b=>{if(b.textContent.trim()==='Stock'||b.textContent.trim()==='Produk')b.classList.toggle('secondary',b.textContent.trim().toLowerCase()!==view)})}}
function renderInventoryBody(){const body=document.getElementById('inventoryBody');if(!body)return;if(inventoryView==='products'){body.innerHTML='<div class="row"><select id="invCat" onchange="renderInventoryBody()"><option value="">Semua Kategori</option><option value="IPHONE_NEW">iPhone New</option><option value="IPHONE_SECOND">iPhone Second</option><option value="ANDROID_NEW">Android New</option><option value="ANDROID_SECOND">Android Second</option></select><input id="invSearch" placeholder="Cari produk / varian / warna" oninput="renderInventoryBody()"></div><div style="margin-top:10px">'+inventoryProducts.filter(p=>(!$('invCat')?.value||p.category===$('invCat').value)&&(!$('invSearch')?.value||[p.product,p.variant,p.color].join(' ').toLowerCase().includes($('invSearch').value.toLowerCase()))).map(p=>'<div class="lead"><b>'+esc(masterProductLabel(p))+'</b><div class="small">'+invCategory(p.category)+'</div></div>').join('')+'</div>';return}const q=($('stockSearch')?.value||'').toLowerCase(),st=$('stockStatus')?.value||'READY';const rows=inventoryStock.filter(s=>(!st||s.status===st)&&(!q||[s.product,s.variant,s.color,s.imei_1,s.imei_2,s.grade,s.condition,s.hunter_name].join(' ').toLowerCase().includes(q)));body.innerHTML='<div class="row"><input id="stockSearch" placeholder="Cari produk, IMEI, grade, warna, hunter..." value="'+esc(q)+'" oninput="renderInventoryBody()"><select id="stockStatus" onchange="renderInventoryBody()"><option value="">Semua Status</option><option>READY</option><option>RESERVED</option><option>SOLD</option><option>SERVICE</option><option>RETURN</option></select></div><div style="margin-top:10px">'+(rows.map(stockCard).join('')||'<p class="small">Belum ada stock.</p>')+'</div>';if($('stockStatus'))$('stockStatus').value=st}
function productShareText(s){const nl=String.fromCharCode(10),c=s.category;let t='📱 '+[s.product,s.variant,s.color].filter(Boolean).join(' • ')+nl;if(c==='IPHONE_SECOND')t+='Grade: '+(s.grade||'-')+nl+'Kondisi: '+(s.condition||'-')+nl+'Battery Health: '+(s.battery_health!=null?s.battery_health+'%':'-')+nl+'Kelengkapan: '+(s.completeness||'-')+nl+'Minus: '+(s.minus||'-')+nl;else if(c==='ANDROID_SECOND')t+='Warna: '+(s.color||'-')+nl+'Kondisi: '+(s.condition||'-')+nl+'Kelengkapan: '+(s.completeness||'-')+nl+'Minus: '+(s.minus||'-')+nl;else if(c==='ANDROID_NEW')t+='Warna: '+(s.color||'-')+nl;t+='IMEI 1: '+(s.imei_1||'-')+nl+'Harga Jual: Rp'+Number(s.asking_price||0).toLocaleString('id-ID')+nl+'Status: '+s.status+nl+nl+'Hello Majesty';return t}
function shareProduct(s){const text=productShareText(s);if(navigator.share){navigator.share({text}).catch(()=>{})}else{navigator.clipboard?.writeText(text);alert('Info produk sudah disalin. Silakan paste ke WhatsApp customer.')}}
function openProductDetail(id){const s=inventoryStock.find(x=>x.id===id);if(!s)return;const c=s.category;let d='';if(c==='IPHONE_SECOND')d='<b>Grade:</b> '+esc(s.grade||'-')+'<br><b>Kondisi:</b> '+esc(s.condition||'-')+'<br><b>Battery Health:</b> '+(s.battery_health!=null?s.battery_health+'%':'-')+'<br><b>Kelengkapan:</b> '+esc(s.completeness||'-')+'<br><b>Minus:</b> '+esc(s.minus||'-')+'<br>';else if(c==='ANDROID_SECOND')d='<b>Warna:</b> '+esc(s.color||'-')+'<br><b>Kondisi:</b> '+esc(s.condition||'-')+'<br><b>Kelengkapan:</b> '+esc(s.completeness||'-')+'<br><b>Minus:</b> '+esc(s.minus||'-')+'<br>';else if(c==='ANDROID_NEW')d='<b>Warna:</b> '+esc(s.color||'-')+'<br>';d+='<b>IMEI 1:</b> '+esc(s.imei_1||'-')+'<br><b>Harga Jual:</b> Rp'+Number(s.asking_price||0).toLocaleString('id-ID');const html=`<div class="box"><h2 style="margin:0">${esc([s.product,s.variant,s.color].filter(Boolean).join(' • '))}</h2><div class="small">${invCategory(s.category)} • ${esc(s.status)}</div></div><div class="lead">${d}</div><div class="row"><button class="success" onclick="shareProduct(inventoryStock.find(x=>x.id===\'${id}\'))">📤 Kirim Info Customer</button>${profile?.role==='SALES'&&s.status==='READY'?'<button class="success" onclick="closeModal();openSellStock(\''+id+'\')">💰 Closing</button>':''}</div>`;$('mt').textContent='📱 Detail Produk';$('mb').innerHTML=html;$('modal').classList.remove('hidden')}
function invCategory(c){return ({IPHONE_NEW:'iPhone New',IPHONE_SECOND:'iPhone Second',ANDROID_NEW:'Android New',ANDROID_SECOND:'Android Second'})[c]||c}
function masterProductLabel(p){const variant=String(p.variant||'').replace(/\s*GB\b/ig,'').trim();const base=[p.product,p.color,variant].filter(Boolean).join(' ');const suffix=p.category==='IPHONE_NEW'?' — NEW':(p.category==='IPHONE_SECOND'?' — SECOND':(p.category==='ANDROID_NEW'?' — NEW':(p.category==='ANDROID_SECOND'?' — SECOND':' — '+(p.category||'').replace('_',' '))));return base+suffix+(p.grade?' — Grade '+p.grade:'')}
function stockCard(s){const management=!!profile?.is_management,facilitator=String(profile?.role||'').toUpperCase()==='FASILITATOR',canViewCost=management||facilitator,ready=s.status==='READY',sales=profile?.role==='SALES',c=s.category,isSecond=c==='IPHONE_SECOND'||c==='ANDROID_SECOND';const title=s.product+(s.variant?' '+s.variant:'')+(s.color?' • '+s.color:'');let meta=invCategory(c);if(c==='IPHONE_SECOND'&&s.grade)meta+=' • Grade '+esc(s.grade);if(isSecond&&s.condition)meta+=' • '+esc(s.condition);if(c==='IPHONE_SECOND'&&s.battery_health!=null)meta+=' • BH '+s.battery_health+'%';meta+=' • IMEI 1 '+esc(s.imei_1||'-');let body='<b>Harga Jual:</b> Rp'+Number(s.asking_price||0).toLocaleString('id-ID');if(isSecond)body='<b>Kelengkapan:</b> '+esc(s.completeness||'-')+'<br><b>Minus:</b> '+esc(s.minus||'-')+'<br>'+body;return '<div class="lead"><div class="row" style="justify-content:space-between"><h3 style="margin:0">'+esc(title)+'</h3><span class="badge">'+esc(s.status)+'</span></div><div class="small">'+meta+'</div><div style="margin-top:8px">'+body+'</div><div class="small" style="margin-top:6px">Sumber: '+(s.source_type==='HUNTER'?'🏹 Hunter — '+esc(s.hunter_name||'-'):'🏢 Management')+(s.status==='SOLD'?' • Terjual '+new Date(s.sold_at).toLocaleDateString('id-ID'):'')+'</div>'+(canViewCost?'<div class="small" style="margin-top:6px">Harga Beli: Rp'+Number(s.cost||0).toLocaleString('id-ID')+'</div>':'')+'<div class="row" style="margin-top:8px"><button class="secondary" onclick="openProductDetail(\''+s.id+'\')">👁️ Detail</button><button class="secondary" onclick="openStockHistory(\''+s.id+'\')">🧾 Histori</button>'+(ready&&sales?'<button class="success" onclick="openSellStock(\''+s.id+'\')">💰 Jual / Closing</button>':'')+(management?'<button class="secondary" onclick="openEditStock(\''+s.id+'\')">Edit</button>':'')+'</div></div>'}
function openProductMaster(){$('mt').textContent='⚙️ Master Produk';$('mb').innerHTML='<button class="success" onclick="openAddProduct()">＋ Tambah Produk</button><div style="margin-top:10px">'+inventoryProducts.map(p=>'<div class="lead"><b>'+esc(masterProductLabel(p))+'</b><div class="small">'+invCategory(p.category)+'</div></div>').join('')+'</div>';$('modal').classList.remove('hidden')}
function openAddProduct(){$('mt').textContent='＋ Master Produk';$('mb').innerHTML='<label>Kategori</label><select id="pmcat" onchange="toggleProductFields()"><option value="IPHONE_NEW">iPhone New</option><option value="IPHONE_SECOND">iPhone Second</option><option value="ANDROID_NEW">Android New</option><option value="ANDROID_SECOND">Android Second</option></select><label>Produk</label><input id="pmprod" placeholder="Contoh: iPhone 17 Pro Max"><label>Varian</label><input id="pmvar" placeholder="256"><div id="pmcolorBox"><label>Warna</label><input id="pmcolor" placeholder="Black"></div><div id="pmgradeBox" class="hidden"><label>Grade (Second)</label><select id="pmgrade"><option value="-">-</option><option>A</option><option>B</option><option>C</option></select></div><button class="success" onclick="saveProduct()">Simpan Produk</button>';toggleProductFields();$('modal').classList.remove('hidden')}
function toggleProductFields(){const cat=$('pmcat')?.value||'',second=cat.includes('SECOND'),iphone=cat.startsWith('IPHONE');$('pmcolorBox')?.classList.toggle('hidden',!iphone);$('pmgradeBox')?.classList.toggle('hidden',!(iphone&&second))}
async function saveProduct(){const cat=$('pmcat').value,isIphone=cat.startsWith('IPHONE'),isSecond=cat.includes('SECOND'),product=$('pmprod').value.trim(),variant=$('pmvar').value.trim();if(!product||!variant)return alert('Produk dan Storage wajib diisi.');const grade=(isIphone&&isSecond)?($('pmgrade').value||'-'):null;const x=await sb.from('product_master').insert({category:cat,product,variant,color:isIphone?($('pmcolor').value.trim()||null):null,grade});if(x.error)return alert(x.error.message);closeModal();await renderInventory();openProductMaster()}
async function openReceiveStock(){
 const teams=await sb.from('team_directory').select('*').order('name');if(teams.error)return alert(teams.error.message);
 const products=inventoryProducts.map(p=>'<option value="'+p.id+'">'+esc(masterProductLabel(p))+'</option>').join('');
 const selected=inventoryProducts.find(p=>p.id===$('stprod')?.value);
 const isIphoneNew=selected?.category==='IPHONE_NEW',isIphoneSecond=selected?.category==='IPHONE_SECOND',isAndroidNew=selected?.category==='ANDROID_NEW';
 const hunters=(teams.data||[]).map(t=>'<option value="'+t.user_id+'">'+esc(t.name)+(t.role?' • '+esc(t.role):'')+'</option>').join('');
 const isMgmt=!!profile?.is_management;const hunterOptions=isMgmt?hunters:'<option value="'+profile.user_id+'">'+esc(profile.name||'Saya')+' • Hunter</option>';
 $('mt').textContent='📦 Barang Masuk';
 $('mb').innerHTML='<label>Produk</label><select id="stprod" onchange="toggleReceiveFields()">'+products+'</select>'+
 '<div id="standardReceiveFields"><label>Sumber</label><select id="stsource"><option value="MANAGEMENT">Management</option><option value="HUNTER">Hunter</option></select><div id="hunterBox" class="hidden"><label>Hunter</label><select id="sthunter" '+(isMgmt?'':'disabled')+'>'+hunterOptions+'</select></div><label>IMEI 1</label><input id="stimei1"><label>IMEI 2 (opsional)</label><input id="stimei2"><label>Kondisi</label><input id="stcondition" placeholder="Contoh: 95% / Mulus"><label>Battery Health</label><input id="stbh" type="number" min="0" max="100" placeholder="89"><label>Kelengkapan</label><input id="stcomplete" placeholder="Unit + Box + Cable"><label>Minus</label><textarea id="stminus"></textarea></div>'+
 '<div id="iphoneNewFields" class="hidden"><label>IMEI 1</label><input id="stimei1new"><label>IMEI 2 / EID (opsional)</label><input id="stimei2new"><label>Harga Beli</label><input id="stcostnew" type="number"><label>Harga Jual</label><input id="stpricenew" type="number"><label>Supplier / Dealer (opsional)</label><input id="stsupplier" placeholder="Nama dealer / supplier"><label>Catatan (opsional)</label><textarea id="stnotesnew"></textarea></div>'+
 '<div id="iphoneSecondFields" class="hidden"><label>IMEI 1</label><input id="stimei1second"><label>IMEI 2 / EID (opsional)</label><input id="stimei2second"><label>Battery Health</label><input id="stbhsecond" type="number" min="0" max="100" placeholder="89"><label>Kondisi</label><input id="stconditionsecond" placeholder="Contoh: Mulus / 95%"><label>Kelengkapan</label><input id="stcompletesecond" placeholder="Unit + Box + Cable"><label>Minus (opsional)</label><textarea id="stminusseconde"></textarea><label>Harga Beli</label><input id="stcostsecond" type="number"><label>Harga Jual</label><input id="stpricesec" type="number"><label>Supplier / Dealer (opsional)</label><input id="stsuppliersecond" placeholder="Nama dealer / supplier"><label>Catatan (opsional)</label><textarea id="stnotessecond"></textarea></div>'+
 '<div id="androidNewFields" class="hidden"><label>Warna</label><input id="standroidcolor" placeholder="Contoh: Violet"><label>IMEI 1</label><input id="standroidimei1"><label>IMEI 2 (opsional)</label><input id="standroidimei2"><label>Harga Beli</label><input id="standroidcost" type="number"><label>Harga Jual</label><input id="standroidprice" type="number"><label>Supplier / Dealer (opsional)</label><input id="standroidsupplier" placeholder="Nama dealer / supplier"><label>Catatan (opsional)</label><textarea id="standroidnotes"></textarea></div>'+
 '<div id="androidSecondFields" class="hidden"><label>Warna</label><input id="standroidsecondcolor" placeholder="Contoh: Black"><label>IMEI 1</label><input id="standroidsecondimei1"><label>IMEI 2 (opsional)</label><input id="standroidsecondimei2"><label>Kondisi</label><input id="standroidsecondcondition" placeholder="Contoh: Mulus / 90%"><label>Kelengkapan</label><input id="standroidsecondcomplete" placeholder="Unit + Box + Cable"><label>Minus (opsional)</label><textarea id="standroidsecondminus"></textarea><label>Harga Beli</label><input id="standroidsecondcost" type="number"><label>Harga Jual</label><input id="standroidsecondprice" type="number"><label>Supplier / Dealer (opsional)</label><input id="standroidsecondsupplier" placeholder="Nama dealer / supplier"><label>Catatan (opsional)</label><textarea id="standroidsecondnotes"></textarea></div><div id="standardPriceFields"><label>Harga Modal</label><input id="stcost" type="number"><label>Harga Jual</label><input id="stprice" type="number"><label>Referensi Barang Masuk</label><input id="stref" placeholder="Invoice / nota / kode hunter"><label>Catatan</label><textarea id="stnotes"></textarea></div><button class="success" onclick="saveStock()">Simpan Stock Ready</button>';
 toggleReceiveFields();
 $('modal').classList.remove('hidden');
}
function toggleReceiveFields(){
 const p=inventoryProducts.find(x=>x.id===$('stprod')?.value),isNew=p?.category==='IPHONE_NEW',isSecond=p?.category==='IPHONE_SECOND',isAndroidNew=p?.category==='ANDROID_NEW',isAndroidSecond=p?.category==='ANDROID_SECOND';
 $('standardReceiveFields')?.classList.toggle('hidden',isNew||isSecond||isAndroidNew||isAndroidSecond);
 $('standardPriceFields')?.classList.toggle('hidden',isNew||isSecond||isAndroidNew||isAndroidSecond);
 $('iphoneNewFields')?.classList.toggle('hidden',!isNew);
 $('iphoneSecondFields')?.classList.toggle('hidden',!isSecond);
 $('androidNewFields')?.classList.toggle('hidden',!isAndroidNew);
 $('androidSecondFields')?.classList.toggle('hidden',!isAndroidSecond);
 const source=$('stsource');if(source)source.onchange=()=>{$('hunterBox')?.classList.toggle('hidden',source.value!=='HUNTER')};
}
async function saveStock(){
 const selectedProduct=inventoryProducts.find(p=>p.id===$('stprod')?.value),isIphoneNew=selectedProduct?.category==='IPHONE_NEW',isIphoneSecond=selectedProduct?.category==='IPHONE_SECOND',isAndroidNew=selectedProduct?.category==='ANDROID_NEW',isAndroidSecond=selectedProduct?.category==='ANDROID_SECOND';
 let data;
 if(isIphoneNew){
  const imei1=$('stimei1new').value.trim(),cost=$('stcostnew').value,price=$('stpricenew').value;
  if(!imei1||cost===''||price==='')return alert('Untuk iPhone New, IMEI 1, Harga Beli dan Harga Jual wajib diisi.');
  data={product_id:$('stprod').value,imei_1:imei1,imei_2:$('stimei2new').value.trim()||null,grade:null,condition:null,battery_health:null,completeness:null,minus:null,source_type:'MANAGEMENT',hunter_user_id:null,cost:Number(cost),asking_price:Number(price),supplier:$('stsupplier').value.trim()||null,notes:$('stnotesnew').value.trim()||null,receipt_ref:null,received_source_note:'Management',outlet:profile?.outlet||null};
 }else if(isIphoneSecond){
  const imei1=$('stimei1second').value.trim(),bh=$('stbhsecond').value,condition=$('stconditionsecond').value.trim(),complete=$('stcompletesecond').value.trim(),cost=$('stcostsecond').value,price=$('stpricesec').value;
  if(!imei1||bh===''||!condition||!complete||cost===''||price==='')return alert('Untuk iPhone Second, IMEI 1, Battery Health, Kondisi, Kelengkapan, Harga Beli dan Harga Jual wajib diisi.');
  data={product_id:$('stprod').value,imei_1:imei1,imei_2:$('stimei2second').value.trim()||null,grade:selectedProduct?.grade||'-',condition,battery_health:Number(bh),completeness:complete,minus:$('stminusseconde').value.trim()||null,source_type:'MANAGEMENT',hunter_user_id:null,cost:Number(cost),asking_price:Number(price),supplier:$('stsuppliersecond').value.trim()||null,notes:$('stnotessecond').value.trim()||null,receipt_ref:null,received_source_note:'Management',outlet:profile?.outlet||null};
 }else if(isAndroidSecond){
  const color=$('standroidsecondcolor').value.trim(),imei1=$('standroidsecondimei1').value.trim(),condition=$('standroidsecondcondition').value.trim(),complete=$('standroidsecondcomplete').value.trim(),cost=$('standroidsecondcost').value,price=$('standroidsecondprice').value;
  if(!color||!imei1||!condition||!complete||cost===''||price==='')return alert('Untuk Android Second, Warna, IMEI 1, Kondisi, Kelengkapan, Harga Beli dan Harga Jual wajib diisi.');
  data={product_id:$('stprod').value,color,imei_1:imei1,imei_2:$('standroidsecondimei2').value.trim()||null,grade:null,condition,battery_health:null,completeness:complete,minus:$('standroidsecondminus').value.trim()||null,source_type:'MANAGEMENT',hunter_user_id:null,cost:Number(cost),asking_price:Number(price),supplier:$('standroidsecondsupplier').value.trim()||null,notes:$('standroidsecondnotes').value.trim()||null,receipt_ref:null,received_source_note:'Management',outlet:profile?.outlet||null};
 }else if(isAndroidNew){
  const color=$('standroidcolor').value.trim(),imei1=$('standroidimei1').value.trim(),cost=$('standroidcost').value,price=$('standroidprice').value;
  if(!color||!imei1||cost===''||price==='')return alert('Untuk Android New, Warna, IMEI 1, Harga Beli dan Harga Jual wajib diisi.');
  data={product_id:$('stprod').value,color,imei_1:imei1,imei_2:$('standroidimei2').value.trim()||null,grade:null,condition:null,battery_health:null,completeness:null,minus:null,source_type:'MANAGEMENT',hunter_user_id:null,cost:Number(cost),asking_price:Number(price),supplier:$('standroidsupplier').value.trim()||null,notes:$('standroidnotes').value.trim()||null,receipt_ref:null,received_source_note:'Management',outlet:profile?.outlet||null};
 }else{
  const source=$('stsource').value,hunter=source==='HUNTER'?$('sthunter').value:null;if(source==='HUNTER'&&!hunter)return alert('Hunter wajib dipilih.');
  data={product_id:$('stprod').value,imei_1:$('stimei1').value.trim()||null,imei_2:$('stimei2').value.trim()||null,grade:selectedProduct?.grade||null,condition:$('stcondition').value.trim()||null,battery_health:$('stbh').value?Number($('stbh').value):null,completeness:$('stcomplete').value.trim()||null,minus:$('stminus').value.trim()||null,source_type:source,hunter_user_id:hunter,cost:Number($('stcost').value||0),asking_price:Number($('stprice').value||0),notes:$('stnotes').value.trim()||null,receipt_ref:$('stref')?.value.trim()||null,received_source_note:source==='HUNTER'?'Hunter':'Management',outlet:profile?.outlet||null};if(source==='HUNTER'&&!profile.is_management)data.hunter_user_id=profile.user_id;
 }
 const x=await sb.from('stock_units').insert(data);if(x.error)return alert(x.error.message);closeModal();await renderInventory();
}
async function openEditStock(id){const s=inventoryStock.find(x=>x.id===id);if(!s)return;const c=s.category;let f=`<div class="small">${esc(s.product)} • IMEI 1: ${esc(s.imei_1||'-')}</div>`;if(c==='IPHONE_SECOND')f+=`<label>Grade</label><select id="esgrade"><option value="-">-</option><option ${s.grade==='A'?'selected':''}>A</option><option ${s.grade==='B'?'selected':''}>B</option><option ${s.grade==='C'?'selected':''}>C</option></select><label>Kondisi</label><input id="escondition" value="${esc(s.condition||'')}"><label>Battery Health</label><input id="esbh" type="number" min="0" max="100" value="${s.battery_health??''}"><label>Kelengkapan</label><input id="escomplete" value="${esc(s.completeness||'')}"><label>Minus</label><textarea id="esminus">${esc(s.minus||'')}</textarea>`;else if(c==='ANDROID_SECOND')f+=`<label>Warna</label><input id="escolor" value="${esc(s.color||'')}"><label>Kondisi</label><input id="escondition" value="${esc(s.condition||'')}"><label>Kelengkapan</label><input id="escomplete" value="${esc(s.completeness||'')}"><label>Minus</label><textarea id="esminus">${esc(s.minus||'')}</textarea>`;else if(c==='ANDROID_NEW')f+=`<label>Warna</label><input id="escolor" value="${esc(s.color||'')}">`;f+=`<label>Harga Jual</label><input id="esprice" type="number" value="${Number(s.asking_price||0)}"><button class="success" onclick="saveEditStock('${id}')">Simpan</button>`;$('mt').textContent='Edit Stock';$('mb').innerHTML=f;$('modal').classList.remove('hidden')}
async function saveEditStock(id){const s=inventoryStock.find(x=>x.id===id);if(!s)return;const c=s.category,data={asking_price:Number($('esprice').value||0),updated_at:new Date().toISOString()};if(c==='IPHONE_SECOND'){data.grade=$('esgrade').value||'-';data.condition=$('escondition').value.trim()||null;data.battery_health=$('esbh').value!==''?Number($('esbh').value):null;data.completeness=$('escomplete').value.trim()||null;data.minus=$('esminus').value.trim()||null}else if(c==='ANDROID_SECOND'){data.color=$('escolor').value.trim()||null;data.condition=$('escondition').value.trim()||null;data.completeness=$('escomplete').value.trim()||null;data.minus=$('esminus').value.trim()||null}else if(c==='ANDROID_NEW'){data.color=$('escolor').value.trim()||null}const x=await sb.from('stock_units').update(data).eq('id',id);if(x.error)return alert(x.error.message);closeModal();await renderInventory()}
async function openStockHistory(id){const x=await sb.from('stock_movements').select('*').eq('stock_unit_id',id).order('created_at',{ascending:false});if(x.error)return alert(x.error.message);$('mt').textContent='🧾 Histori Stock';$('mb').innerHTML=(x.data||[]).map(m=>'<div class="lead"><b>'+esc(m.movement_type)+'</b><div class="small">'+new Date(m.created_at).toLocaleString('id-ID')+' • '+esc(m.from_status||'-')+' → '+esc(m.to_status||'-')+'</div><div>'+esc(m.note||'')+'</div></div>').join('')||'<p class="small">Belum ada histori.</p>';$('modal').classList.remove('hidden')}
async function openSalesReport(){const x=await sb.from('sales_transactions').select('*').order('sold_at',{ascending:false});if(x.error)return alert(x.error.message);const rows=x.data||[],total=rows.reduce((a,r)=>a+Number(r.sale_price-r.discount),0),profit=rows.reduce((a,r)=>a+Number(r.gross_profit),0),comm=rows.reduce((a,r)=>a+Number(r.hunter_commission),0);$('mt').textContent='📊 Laporan Penjualan';$('mb').innerHTML='<div class="stats">'+invStat('Omzet',total)+invStat('Laba',profit)+invStat('Komisi Hunter',comm)+'</div>'+rows.map(r=>'<div class="lead"><b>'+new Date(r.sold_at).toLocaleDateString('id-ID')+'</b><div class="small">Sumber: '+(r.customer_source==='WALK-IN'?'🚶 WALK-IN':'📱 DIGITAL')+' • Sales: '+esc(r.sales_user_id||'-')+' • Hunter: '+esc(r.hunter_user_id||'-')+'</div><div>Jual Rp'+Number(r.sale_price-r.discount).toLocaleString('id-ID')+' • Laba Rp'+Number(r.gross_profit).toLocaleString('id-ID')+' • Komisi Rp'+Number(r.hunter_commission).toLocaleString('id-ID')+'</div></div>').join('')||'<p class="small">Belum ada penjualan.</p>';$('modal').classList.remove('hidden')}
